name: CI-CD-Pipeline

on:
  push:
    branches:
      - '**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Build and Push Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vote:latest ./vote
          docker build -t ${{ secrets.DOCKER_USERNAME }}/result:latest ./result
          docker build -t ${{ secrets.DOCKER_USERNAME }}/worker:latest ./worker
          docker push ${{ secrets.DOCKER_USERNAME }}/vote:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/result:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/worker:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name wale-voting-app-eks --region eu-central-1

      - name: Create K8s Secret from GitHub
        run: |
          kubectl create secret generic voting-app-secrets \
            --from-literal=postgres-user='postgres' \
            --from-literal=postgres-password='${{ secrets.DB_PASSWORD }}' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s-manifests/

          # This overrides the 'latest' tag in your YAMLs with the branch tag
          kubectl set image deployment/vote vote=${{ secrets.DOCKER_USERNAME }}/vote:${{ env.BRANCH_NAME }}
          kubectl set image deployment/result result=${{ secrets.DOCKER_USERNAME }}/result:${{ env.BRANCH_NAME }}
          kubectl set image deployment/worker worker=${{ secrets.DOCKER_USERNAME }}/worker:${{ env.BRANCH_NAME }}
